# Generated by Django 2.1.4 on 2018-12-20 22:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gl_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='complete_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 20, 22, 36, 24, 436593, tzinfo=utc)),
        ),
    ]
