# Generated by Django 2.1.4 on 2018-12-20 22:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gl_app', '0002_auto_20181220_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
