# Generated by Django 2.1.4 on 2018-12-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gl_app', '0003_auto_20181220_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
