# Generated by Django 2.1.4 on 2018-12-31 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gl_app', '0004_auto_20181220_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryitem',
            old_name='name',
            new_name='gcname',
        ),
    ]
