# Generated by Django 2.1.5 on 2019-01-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jomei_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='location',
        ),
        migrations.AddField(
            model_name='point',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=45.5022952, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=-122.671401, max_digits=9),
            preserve_default=False,
        ),
    ]
