# Generated by Django 2.1.5 on 2019-01-18 22:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jomei_app', '0002_auto_20190118_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date_created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='point',
            name='last_modified_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='last_date_modified'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlocationpoint',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date_created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlocationpoint',
            name='last_modified_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='last_date_modified'),
            preserve_default=False,
        ),
    ]
