# Generated by Django 2.1.5 on 2019-01-16 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jomei_app', '0002_auto_20190116_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='layer',
        ),
        migrations.DeleteModel(
            name='Layer',
        ),
    ]
