# Generated by Django 2.1.5 on 2019-01-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jomei_app', '0003_auto_20190116_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='id',
        ),
        migrations.AddField(
            model_name='point',
            name='distance_away',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
