# Generated by Django 2.1.5 on 2019-01-16 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jomei_app', '0004_auto_20190116_1343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Point',
        ),
    ]
