# Generated by Django 2.1.5 on 2019-01-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='in_basket',
            new_name='obtained',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_text',
            field=models.CharField(max_length=32),
        ),
    ]
