# Generated by Django 2.1.5 on 2019-01-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0002_auto_20190108_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_text',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='item',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date completed'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1),
        ),
    ]
