# Generated by Django 2.1.5 on 2019-01-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appymodel',
            name='cell_phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='appymodel',
            name='home_phone',
            field=models.CharField(max_length=10),
        ),
    ]
