# Generated by Django 2.1.5 on 2019-01-14 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appy', '0003_auto_20190111_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appymodel',
            old_name='previous_state',
            new_name='previous_state_abv',
        ),
    ]
