# Generated by Django 2.1.5 on 2019-01-21 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appy', '0008_auto_20190118_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('home_phone', models.CharField(max_length=10)),
                ('cell_phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('problem_description', models.CharField(max_length=1000)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
