# Generated by Django 2.1.5 on 2019-01-22 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appy', '0009_maintymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintymodel',
            name='date_time_form_filled',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
