# Generated by Django 2.1.4 on 2019-01-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_short_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='click_counter',
            field=models.IntegerField(default=0),
        ),
    ]
