# Generated by Django 2.1.4 on 2019-01-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_short_app', '0002_urlshortener_click_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0', protocol='IPv4'),
        ),
    ]
