# Generated by Django 2.1.5 on 2019-01-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unpack_ipv4=True)),
                ('time_searched', models.TimeField(auto_now=True)),
                ('censys_result', models.TextField(blank=True)),
                ('shodan_result', models.TextField(blank=True)),
            ],
        ),
    ]
