# Generated by Django 2.1.5 on 2019-01-07 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0002_post_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pub_date',
        ),
    ]
