# Generated by Django 2.1.5 on 2019-01-07 23:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0003_remove_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 7, 23, 26, 17, 718333, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
