# Generated by Django 2.1 on 2019-01-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_long_path', models.TextField()),
                ('url_short_path', models.TextField()),
            ],
        ),
    ]
