# Generated by Django 2.1.5 on 2019-01-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=60)),
                ('rating_number', models.DecimalField(decimal_places=1, max_digits=3)),
                ('rating_name', models.CharField(max_length=60)),
                ('workout_type', models.CharField(max_length=60)),
                ('workout_muscle', models.CharField(max_length=60)),
                ('workout_equipment', models.CharField(max_length=60)),
                ('workout_level', models.CharField(max_length=60)),
                ('workout_img_1', models.CharField(max_length=200)),
                ('workout_img_2', models.CharField(max_length=200)),
                ('muscle_group_img', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
            ],
        ),
    ]
