# Generated by Django 2.1.4 on 2019-01-17 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=60)),
                ('rating_number', models.CharField(max_length=6)),
                ('rating_name', models.CharField(max_length=60)),
                ('workout_type', models.CharField(max_length=60)),
                ('workout_muscle', models.CharField(max_length=60)),
                ('workout_equipment', models.CharField(max_length=60)),
                ('workout_level', models.CharField(max_length=60)),
                ('workout_img_1', models.CharField(max_length=200)),
                ('workout_img_2', models.CharField(max_length=200)),
                ('muscle_group_img', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ManyToManyField(to='easyfitness_app.Workout'),
        ),
    ]
